using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace RabbitSoft2
{
    public partial class DataScreens : DevExpress.XtraEditors.XtraUserControl
    {
        public DataScreens()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            ledgerTableAdapter1.Fill(rabbiT_RIDESHAREDataSet1.LEDGER);
            // This line of code is generated by Data Source Configuration Wizard
            mileagelogTableAdapter1.Fill(rabbiT_RIDESHAREDataSet2.MILEAGELOG);
            // This line of code is generated by Data Source Configuration Wizard
            trip_ActivityTableAdapter1.Fill(rabbiT_RIDESHAREDataSet3.Trip_Activity);
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            using (SqlConnection connection = new SqlConnection("Data Source=RABBIT_DESKTOP\\SQLEXPRESS;Initial Catalog=RABBIT_RIDESHARE;Integrated Security=True;TrustServerCertificate=True"))
            {
                connection.Open();
                string sqlQuery = "SELECT * FROM LEDGER";

                using (SqlDataAdapter adapter = new SqlDataAdapter(sqlQuery, connection))
                {
                    SqlCommandBuilder commandBuilder = new SqlCommandBuilder(adapter);
                    adapter.Update(rabbiT_RIDESHAREDataSet1.LEDGER);
                }

                connection.Close();
            }
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            using (SqlConnection connection = new SqlConnection("Data Source=RABBIT_DESKTOP\\SQLEXPRESS;Initial Catalog=RABBIT_RIDESHARE;Integrated Security=True;TrustServerCertificate=True"))
            {
                connection.Open();
                string sqlQuery = "SELECT * FROM Trip_Activity";

                using (SqlDataAdapter adapter = new SqlDataAdapter(sqlQuery, connection))
                {
                    SqlCommandBuilder commandBuilder = new SqlCommandBuilder(adapter);
                    adapter.Update(rabbiT_RIDESHAREDataSet3.Trip_Activity);
                }

                connection.Close();
            }
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            using (SqlConnection connection = new SqlConnection("Data Source=RABBIT_DESKTOP\\SQLEXPRESS;Initial Catalog=RABBIT_RIDESHARE;Integrated Security=True;TrustServerCertificate=True"))
            {
                connection.Open();
                string sqlQuery = "SELECT * FROM MILEAGELOG";

                using (SqlDataAdapter adapter = new SqlDataAdapter(sqlQuery, connection))
                {
                    SqlCommandBuilder commandBuilder = new SqlCommandBuilder(adapter);
                    adapter.Update(rabbiT_RIDESHAREDataSet2.MILEAGELOG);
                }

                connection.Close();
            }
        }
    }
}
