using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace RabbitSoft2.REPORTS
{
    public partial class MileageLogBook : DevExpress.XtraEditors.XtraUserControl
    {
        public MileageLogBook()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            mILEAGELOGTableAdapter.Fill(rABBIT_RIDESHAREDataSet.MILEAGELOG);
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {

            using (SqlConnection connection = new SqlConnection("Data Source=RABBIT_DESKTOP\\SQLEXPRESS;Initial Catalog=RABBIT_RIDESHARE;Integrated Security=True;TrustServerCertificate=True"))
            {
                connection.Open();

                for (int i = 0; i < gridView2.RowCount; i++)
                {
                    DataRowView row = gridView2.GetRow(i) as DataRowView;

                    if (row.Row.RowState == DataRowState.Modified)
                    {

                        using (SqlCommand command = new SqlCommand("UPDATE MILEAGELOG SET STARTMILES = @STARTMILES, ENDMILES = @ENDMILES, TOTALMILES = @TOTALMILES WHERE ID = @ID", connection))
                        {
                            command.Parameters.AddWithValue("@ID", Convert.ToInt32(row[0].ToString()));
                            command.Parameters.AddWithValue("@STARTMILES", Convert.ToInt32(row[5].ToString()));
                            command.Parameters.AddWithValue("@ENDMILES", Convert.ToInt32(row[6].ToString()));

                            int totalmiles = Convert.ToInt32(row[6].ToString()) - Convert.ToInt32(row[5].ToString());
                            command.Parameters.AddWithValue("@TOTALMILES", totalmiles);

                            command.ExecuteNonQuery();
                        }
                    }
                }
                connection.Close();
            }
        }
    }
}
