using DevExpress.DataAccess.Sql;
using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace RabbitSoft2
{
    public partial class Bills : DevExpress.XtraEditors.XtraUserControl
    {
        public Bills()
        {
            InitializeComponent();

            // TODO: This line of code loads data into the 'rABBIT_RIDESHAREDataSet.Resources' table. You can move, or remove it, as needed.
            this.resourcesTableAdapter.Fill(this.rABBIT_RIDESHAREDataSet.Resources);
            // TODO: This line of code loads data into the 'rABBIT_RIDESHAREDataSet.Appointments' table. You can move, or remove it, as needed.
            this.appointmentsTableAdapter.Fill(this.rABBIT_RIDESHAREDataSet.Appointments);
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            //sqlDataSource1.FillAsync();
        }
    }
}
