using DevExpress.Data.Filtering;
using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace RabbitSoft2
{
    public partial class Ledger2 : DevExpress.XtraEditors.XtraUserControl
    {
        public Ledger2(int month, int year)
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            ledgerTableAdapter1.Fill(rabbiT_RIDESHAREDataSet1.LEDGER);

            var filter = CriteriaOperator.Parse("GetMonth([Date]) = ? AND GetYear([Date]) = ?", month, year);
            gridView1.ActiveFilterCriteria = filter;
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            using (SqlConnection connection = new SqlConnection("Data Source=RABBIT_DESKTOP\\SQLEXPRESS;Initial Catalog=RABBIT_RIDESHARE;Integrated Security=True;TrustServerCertificate=True"))
            {
                connection.Open();
                string sqlQuery = "SELECT * FROM LEDGER";

                using (SqlDataAdapter adapter = new SqlDataAdapter(sqlQuery, connection))
                {
                    SqlCommandBuilder commandBuilder = new SqlCommandBuilder(adapter);
                    adapter.Update(rabbiT_RIDESHAREDataSet1.LEDGER);
                }

                connection.Close();
            }
        }
    }
}
