using DevExpress.Data.Filtering;
using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace RabbitSoft2
{
    public partial class Ledger : DevExpress.XtraEditors.XtraUserControl
    {
        public Ledger(int month, int year)
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();

            var filter = CriteriaOperator.Parse("GetMonth([Date]) = ? AND GetYear([Date]) = ?", month, year);
            gridView1.ActiveFilterCriteria = filter;

        }
    }
}
