using DevExpress.XtraEditors;
using DevExpress.XtraGrid;
using DevExpress.XtraGrid.Views.Grid;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace RabbitSoft
{
    public partial class Ledger : DevExpress.XtraEditors.XtraUserControl
    {
        public Ledger()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
            gridView1.OptionsSelection.EnableAppearanceFocusedRow = false;

        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }
    }
}
