using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace RabbitSoft
{
    public partial class UberDeliveriesViewData : DevExpress.XtraEditors.XtraUserControl
    {
        public UberDeliveriesViewData()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void UberDeliveriesViewData_Load(object sender, EventArgs e)
        {

        }
    }
}
