using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace RabbitSoft2
{
    public partial class DataScreens : DevExpress.XtraEditors.XtraUserControl
    {
        public DataScreens()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            ledgerTableAdapter1.Fill(rabbiT_RIDESHAREDataSet1.LEDGER);
            // This line of code is generated by Data Source Configuration Wizard
            mileagelogTableAdapter1.Fill(rabbiT_RIDESHAREDataSet2.MILEAGELOG);
            // This line of code is generated by Data Source Configuration Wizard
            trip_ActivityTableAdapter1.Fill(rabbiT_RIDESHAREDataSet3.Trip_Activity);
        }
    }
}
